-- phpMyAdmin SQL Dump
-- version 4.1.12
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Apr 22, 2015 at 12:10 PM
-- Server version: 5.6.16
-- PHP Version: 5.5.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `web-lims`
--
-- pima controls

-- --------------------------------------------------------

--
-- Table structure for table `pima_control`
--

CREATE TABLE IF NOT EXISTS `pima_control` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_test_id` int(11) NOT NULL COMMENT 'Generated by the pima device',
  `pima_upload_id` int(11) NOT NULL COMMENT 'FK to pima Upload',
  `assay_id` int(11) NOT NULL,
  `sample_code` varchar(100) NOT NULL,
  `error_id` int(11) NOT NULL,
  `operator` varchar(100) NOT NULL,
  `barcode` int(11) NOT NULL,
  `expiry_date` int(11) NOT NULL,
  `device` int(11) NOT NULL,
  `software_version` varchar(50) NOT NULL,
  `cd4_count` int(11) NOT NULL,
  `facility_equipment_id` int(11) NOT NULL COMMENT 'fk to facility_equipment',
  `result_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COMMENT='Pima Test uploads' AUTO_INCREMENT=1 ;

