CREATE TABLE `pima_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cd4_test_id` int(11) NOT NULL COMMENT 'FK_to cd4_test',
  `device_test_id` int(11) NOT NULL COMMENT 'Generated by the pima device',
  `pima_upload_id` int(11) NOT NULL COMMENT 'FK to pima Upload',
  `assay_id` int(11) NOT NULL,
  `sample_code` varchar(100) NOT NULL,
  `error_id` int(11) NOT NULL,
  `operator` varchar(100) NOT NULL,
  `barcode` int(11) NOT NULL,
  `expiry_date` int(11) NOT NULL,
  `volume` int(11) NOT NULL,
  `device` int(11) NOT NULL,
  `reagent` int(11) NOT NULL,
  `software_version` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='Pima Test uploads'